#include "global_macros.h"

#include "stm32f4xx_rcc.h"
#include "stm32f4xx_global_macros.h"
#include "stm32f4xx.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_tim.h"
#include "stm32f4xx_adc.h"
#include "stm32f4xx_dma.h"
#include "stm32f4xx_usart.h"
#include "stm32f4xx_flash.h"
#include "stm32f4xx_syscfg.h"
#include "stm32f4xx_exti.h"
#include "math.h"
#include "string.h"

